spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/emlakjetdb
    type: com.mysql.cj.jdbc.MysqlDataSource
    password: Voda2917
app:
  limit: 200